### PR TITLE
Keyboard accessibility features

### PR DESCRIPTION
**Pull request by aceyoung9**
Hi! I use your Floss Color Tool, and I also can't reliably use a mouse (wrist pain problems).

### Features

* All the color rows are tabbable
* If you hit space or enter while a keyboard is tabbable, the color accordion opens.
* `role=button` for people who use Vimium
* Snuck in a <title> update.

Thank you!

### CODE REVIEW

**Comment by hoovercj** [comment]
Hi @aceyoung9, I'm sorry that you find the site hard to use due to lack of keyboard support! I really appreciate that you took the initiative to make an improvement and I regret that I didn't see this sooner. I've just added a handful of new features to the page such as a list of substitutes for anchor colors, anchor/dmc equivalents, and the ability to link to a specific color. Now that I have these additional changes, I need to think a bit more about I want the site to look (there are some accessibility issues related to low-contrast which I need to solve!) and how I want the keyboard experience to be, and now that I've seen your PR, you've given me the motivation to do it sooner rather than later.

I'll let you know when I sit back down to work on this and decide what the best solution is. It might be exactly what you've suggested or it might be something a little different, but I'll make sure that it addresses your needs.

**Comment by hoovercj** [comment]
Hi @aceyoung9, I actually decided to power through it this evening and push out some additional keyboard and layout improvements that I hope will help.

I'm going to close this PR for now because I believe I've addressed the issue, but if I haven't fixed it well enough or if you have any other problems please open an issue!

**Comment by aceyoung9** [comment]
Poked around on the updated site; works well on my end! Thanks!

**Comment by hoovercj** [comment]
@aceyoung9 glad to hear it, thanks!

**Pull request closed without merging**
